---
title: "DSjobtracker: What are the qualifications and skills that a data scientist, statistician, or data analyst must possess?"
output: 
  flexdashboard::flex_dashboard:
    orientation: column
    vertical_layout: fill
---
<style>
.tab-content{
position:relative;
top:50px;
}
</style>
```{r setup, include=FALSE}
library(flexdashboard)
library(wordcloud)
library(wordcloud2)
library(tm)
library(RColorBrewer)
library(stringr)
library(tidyverse)
library(plotly)
library(data.table)
library(countrycode)
library(quantmod)
library(formattable)

df <- read_csv("DStidy_2022.csv")
```

Overview
======================================================
Column
-----------------------------------------------------------------------

### Job Title


### Education Qualification

Column
-----------------------------------------------------------------------

### Knowledge Base


### Company Location



Spatial Distributions
======================================================

Row 
-------------------------------------

### Spatial Distribution of proportion of Job Advertisments
    

### Advertisment Distribution by country



Row {.tabset .tabset-fade}
-------------------------------------
   
### Spatial Distribution by Job Type

 
### Spatial Distribution of Salary

*The minimum annual salary of each country in USD
    



Job Fields
======================================================

Column
--------------------------------------------------------------

### Composition of Job Fields



Column {.tabset .tabset-fade}
--------------------------------------------------------------

### R and Python Requirements of Job Fields


### Tableau and Microsoft Power BI Requirements of Job Fields


### Minimum experience needed in Job Fields


English Requirement
======================================================

## Column {data-width=500}
--------------------------------------------------------------

### English Requirement by Country



## Column {data-width=500, .tabset}
--------------------------------------------------------------

### English Requirement by Job Field


### English Requirement by Job Category




Soft Skills
======================================================

Column {data-width=350}
-----------------------------------------------------------------------

### Composition of demanded Soft Skills


Column {data-width=650}
-----------------------------------------------------------------------

### Demanded Soft Skills according to the Job Field





Experience
======================================================

column{}
----------------------------------------------------------------------

### Distribution of Minimun Years of Experience


column{.tabset}
-----------------------------------------------------------------------

### Distribution of Experience by Job Category


### Distribution of Experience by Educational Qualifications






Software and Skills
======================================================


Column {data-width=500}
-----------------------------------------------------------------------

### Top 20 skills required in jobs


Column {data-width=500}
-----------------------------------------------------------------------

### Soft skills required in jobs




Software Skills
======================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Statistical softwares


Column {data-width=500}
-----------------------------------------------------------------------

### Database and Query languages






Knowledge and Skills
======================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Treemap of Konwledge and skills



Column {data-width=350}{.tabset .tabset-fade}
-----------------------------------------------------------------------

### Required Knowledge according to job category


### Required Skills according to job category





Education
======================================================

Column {data-width=200, .tabset}
-----------------------------------------------------------------------

### Educational Qualifications






Salary 
=====================================

Row
-------------------------------------

### Distibution of Average of Minimum Salaries by Job 


Row
------------------------------------
### Distibution of Average of Minimum Salaries by Countries




Our Team
======================================================


